- name: Enabling redis
  ansible.builtin.command: dnf module enable redis:7 -y
- name: installing redis
  ansible.builtin.dnf:
    name: redis
    state: present
- name: allowing remote connections
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
- name: allowing remote connections
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: 'protected-mode yes'
    replace: 'protected-mode no'
- name: starting redis
  ansible.builtin.service:
    name: redis
    state: restarted
    enabled: yes