- name: copy mongo repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo
- name: install mongo db
  ansible.builtin.dnf:
    name: mongodb-org
    state: present
- name: enable and starting mongo
  ansible.builtin.service:
    name: mongod
    state: restarted
    enabled: true
- name: allowing remote connnections
  ansible.builtin.replace:
    path: /etc/mongo.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0' 