[mongodb]
mongodb-dev.anildevops.online

[frontend]
frontend-dev.anildevops.online

[catalogue]
catalogue-dev.anildevops.online

[user]
user-dev.anildevops.online

[cart]
cart-dev.anildevops.online

[local]
localhost