- name: copyig rabbitmq.repo 
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo
- name: installing rabbitmq
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: present
- name: enabling and starting
  ansible.builtin.service:
    name: rabbitmq-server
    state: restarted
    enabled: true
- name: Ensure roboshop user exists in RabbitMQ natively
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: "{{ RABBIT_MQ_PASS }}"
    vhost: /
    configure_priv: ".*"
    read_priv: ".*"
    write_priv: ".*"
    state: present