- name: configuring mysql
  hosts: mysql
  become: yes
  tasks:
    - name: installing mysql server
      ansible.builtin.dnf:
        name: mysql-server
        state: present
    - name: enabling and starting mysql server 
      ansible.builtin.service:
        name: mysqld
        state: restarted
        enabled: true
    - name: setting root with password
      ansible.builtin.command: mysql_secure_installation --set-root-pass "{{ SQL_ROOT_PASS }}"
      ignore_errors: true

  